apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: {{ template "fullname" . }}-rewrite-config-vol
          configMap:
            name: {{ template "fullname" . }}-rewrite-config
        - name: {{ template "fullname" . }}-nginx-secret-vol 
          secret:
            secretName: {{ template "fullname" . }}-nginx-secret
        - name: {{ template "fullname" . }}-notebook-config-vol
          configMap:
            name: {{ template "fullname" . }}-notebook-config
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.existingClaim }}
        {{ end }}  
      containers:
        - name: proxy-rewriter
          image: rlaurika/openshift-nginx
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: {{ template "fullname" . }}-rewrite-config-vol
              mountPath: /etc/nginx/conf.d
            - name: {{ template "fullname" . }}-nginx-secret-vol
              mountPath: /etc/nginx/secrets
        - name: jupyter
          image: {{ .Values.dockerImage }}
          env:
          {{ if .Values.env.jupyterLab }}
          - name: JUPYTER_ENABLE_LAB
            value: "1"
          {{ end }}
          - name: SPARK_MASTER_SERVICE
            value: {{ .Values.env.sparkMasterUrl }}
          - name: SPARK_OPTS
            value: --master={{ .Values.env.sparkMasterUrl }}
          - name: SPARK_DRIVER_MEMORY   # Need to set these values according to allocated resources
            value: 1g
          - name: SPARK_DRIVER_CORES
            value: '1'
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 1Gi
          ports:
          - containerPort: 8888
          volumeMounts:
          - name: {{ template "fullname" . }}-notebook-config-vol
            mountPath: /home/notebook/.jupyter
          {{- if ne .Values.persistentStorage.existingClaim "" }}
          - name: {{ .Values.persistentStorage.existingClaimName }}
            mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
          {{- end -}}
