{{- if .Values.openshift.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "jupyterhub.hub.fullname" . }}-route
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ template "jupyterhub.proxy-public.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.openshift.route.termination_type | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.route.termination_policy | default "Redirect" }}
  wildcardPolicy: None
{{- end }}