# HedgeDoc PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: hedgedoc
  name: uploads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hedgedoc.pvc.storageSpace }}
---