apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgresql
  name: postgres
{{- if .Values.hedgedoc.secret }}
data:
  {{- range $key, $val := .Values.hedgedoc.secret }}
    "{{ $key }}": "{{ tpl $val $ | b64enc }}"
  {{- end }}
{{- end }}
type: Opaque