apiVersion: v1
stringData:
  database-name: postgres
  database-user: postgres
  {{- include "hedgedoc.postgresPassword" . | nindent 2 }}
kind: Secret
metadata:
  labels:
    app: postgresql
  name: postgres
type: Opaque