apiVersion: v1
stringData:
  database-name: {{ .Values.secret.databaseName }}
  database-password: {{ .Values.secret.password | b64enc }}
  database-user: {{ .Values.secret.databaseUser }}
kind: Secret
metadata:
  labels:
    app: postgresql-persistent
  name: {{ .Values.secret.name }}
type: Opaque