apiVersion: v1
stringData:
  database-name: {{ .Values.secret.databaseName }}
  database-user: {{ .Values.secret.databaseUser }}
  {{- include "hedgedoc.postgresPassword" . | nindent 2 }}
kind: Secret
metadata:
  labels:
    app: postgresql-persistent
  name: {{ .Values.secret.name }}
type: Opaque