{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgresql
  name: postgres
data:
  database-name: {{ .Values.postgresql.auth.database | b64enc | quote }}
  database-user: {{ .Values.postgresql.auth.username | b64enc | quote }}
  database-password: {{ .Values.hedgedoc.secret.databasePassword | default ( include "random_pw_reusable" . ) | b64enc | quote }}
  password: {{ .Values.hedgedoc.secret.password | default ( include "random_pw_reusable" . ) | b64enc | quote }}
  postgres-password: {{ .Values.hedgedoc.secret.postgresPassword | default ( include "random_pw_reusable" . ) | b64enc | quote }}
type: Opaque
{{- end }}

{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgresql
  name: postgres
data:
  {{- range $key, $val := .Values.postgresqlExternal.secret }}
    "{{ $key }}": "{{ tpl $val $ | b64enc }}"
  {{- end }}
type: Opaque
{{- end }}
