# HedgeDoc SERVICE
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hedgedoc
  name: hedgedoc
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: hedgedoc
  type: {{ .Values.hedgedoc.service.type }}
---

# PostgreSQL SERVICE
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgresql
  type: {{ .Values.postgres.service.type }}
