# HedgeDoc SERVICE
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hedgedoc
  name: hedgedoc
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: hedgedoc
  type: ClusterIP
---