apiVersion: v2
name: rocketchat
dependencies:
  - name: rocketchat
    repository: https://rocketchat.github.io/helm-charts
    version: 7.0.x
version: 2.0.0
description: Rcoket.Chat Helm Chart for Rahti platform
  Link to the repo https://github.com/CSCfi/helm-charts
icon: https://raw.githubusercontent.com/RocketChat/Rocket.Chat.Artwork/master/Logos/icon.svg
sources:
  - https://github.com/CSCfi/helm-charts
