# Rahti route configuration
route:
  enabled: true
  host: "" # Edit this value to set the route host, e.g. "my-rocketchat.rahtiapp.fi"
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

# Rocket.Chat configuration
rocketchat:
  image:
    repository: rocketchat/rocket.chat
  pullPolicy: IfNotPresent

  replicaCount: 1
  minAvailable: 1

  smtp:
    enabled: false
    host: ""
    port: 587
    username: ""
    password: ""

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi

  resources:
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: 2Gi
      cpu: 1

  securityContext:
    runAsUser: null
    fsGroup: null

  containerSecurityContext:
    runAsUser: null

  podMonitor:
    enabled: false

  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

  ##### MONGODB CONFIGURATION #####
  ## Currently, the chart uses Bitnami's MongoDB chart version 13.x.x as a dependency.
  ## You can check all the values with command: helm show values bitnami/mongodb --version 13.x.x
  mongodb:
    enabled: true
    image:
      registry: satama.csc.fi
      repository: library/mongodb
      tag: 8.3.4
    tls:
      enabled: false
    externalAccess:
      autoDiscovery:
        image:
          registry: docker.io
          repository: bitnamilegacy/kubectl
    dnsCheck:
      image:
        repository: bitnamilegacy/os-shell
    volumePermissions:
      enabled: false
      image:
        repository: bitnamilegacy/os-shell
    initdbScriptsConfigMap: rocketchat-mongodb-fix-clustermonitor-role-configmap
    auth:
      rootPassword: ""
      usernames:
        - rocketchat
      passwords: []
      databases:
        - rocketchat
    architecture: replicaset
    replicaCount: 1
    metrics:
      enabled: false
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false

  # # # # # # # # # # # # # # # # #
  #   M I C R O S E R V I C E S   #
  #  Only available to E.E users  #
  # # # # # # # # # # # # # # # # #
  microservices:
    enabled: false

  nats:
    enabled: false
