apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-nginx-secret
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  passwd: |-
    {{ .Files.Get "creds" | b64enc }}
