apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ template "fullname" . }}-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-master
        group: {{ template "fullname" . }}
    spec:
      volumes:
        - name: {{ template "fullname" . }}-rewrite-config-vol
          configMap:
            name: {{ template "fullname" . }}-nginx-config
            items:
            - key: default.conf
              path: default.conf
        - name: {{ template "fullname" . }}-nginx-secret-vol
          secret:
            secretName: {{ template "fullname" . }}-nginx-secret
        {{ if ne .Values.persistentStorage.existingClaim "" }}
        - name: {{ .Values.persistentStorage.existingClaimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.existingClaim }}
        {{ end }}
      {{- if ne .Values.persistentStorage.existingClaim "" }}
      initContainers:
      - name: busybox
        image: busybox:1
        args:
          - "/bin/mkdir"
          - "-p"
          - "/mnt/{{ .Values.persistentStorage.existingClaimName }}/.tools/{{ template "fullname" . }}/master"
        volumeMounts:
        - name: {{ .Values.persistentStorage.existingClaimName }}
          mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
      {{- end }}
      containers:
        - name: proxy-rewriter
          image: rlaurika/openshift-nginx
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi
          ports:
            - containerPort: 9001
          volumeMounts:
            - name: {{ template "fullname" . }}-rewrite-config-vol
              mountPath: /etc/nginx/conf.d
            - name: {{ template "fullname" . }}-nginx-secret-vol
              mountPath: /etc/nginx/secrets
        - name: spark-master
          image: {{ .Values.masterImage }}
          imagePullPolicy: Always
          ports:
            - containerPort: 7077
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            requests:
                cpu: {{ .Values.master.resources.requests.cpu }}
                memory: {{ .Values.master.resources.requests.memory }}
            limits:
                cpu: {{ .Values.master.resources.limits.cpu }}
                memory: {{ .Values.master.resources.limits.memory }}
          env:
            - name: START_COMMAND
              value: "/usr/local/bin/start-master.sh"
            - name: SPARK_PUBLIC_DNS
              value: {{ .Values.ingress.host }}
          {{- if ne .Values.persistentStorage.existingClaim "" }}
            - name: SPARK_RECOVERY_DIR
              value: /mnt/{{ .Values.persistentStorage.existingClaimName }}/.tools/{{ template "fullname" . }}/master
          volumeMounts:
          - name: {{ .Values.persistentStorage.existingClaimName }}
            mountPath: /mnt/{{ .Values.persistentStorage.existingClaimName }}
          {{- end }}
