apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default
data:
  default.conf: |
    server {
      listen 8081;
      server_name {{ tpl .Values.rstudio.route.host . }}.2.rahtiapp.fi;
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        auth_basic \"Rstudio\";
        auth_basic_user_file /etc/nginx/secret/htpasswd;
        proxy_pass http://{{ tpl .Values.appName . }}:8787/;
        proxy_set_header Host $http_host;
        client_max_body_size 2000M;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
