apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccount: build-reader
      initContainers:
      - name: wait-for-build
        imagePullPolicy: IfNotPresent
        image: quay.io/openshift/origin-cli:4.16
        command:
        - sh
        - -c
        - oc wait --for=jsonpath='{.status.phase}'=Complete build -l buildconfig={{ .Values.appName }} --timeout=900s
      containers:
      - name: {{ .Values.appName }}
        imagePullPolicy: IfNotPresent
        image: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/{{ .Values.appName }}:latest
        ports:
        - containerPort: 3838
          protocol: TCP
        - containerPort: 8787
          protocol: TCP
        volumeMounts:
        - name: {{ .Values.rstudio.pvc.mountName }}
          mountPath: /home/rstudio-server
        - name: {{ .Values.shiny.pvc.mountName }}
          mountPath: /srv/shiny-server
        {{- if .Values.openshift.enabled}}
        securityContext:
        {{- .Values.rstudio.containerSecurityContext | toYaml | nindent 10 }}
        {{- end }}
      restartPolicy: Always
      {{- if .Values.openshift.enabled }}
      securityContext:
      {{- .Values.rstudio.podSecurityContext | toYaml | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ .Values.rstudio.pvc.mountName }}
        persistentVolumeClaim:
          claimName: {{ .Values.rstudio.pvc.mountName }}
      - name: {{ .Values.shiny.pvc.mountName }}
        persistentVolumeClaim:
          claimName: {{ .Values.shiny.pvc.mountName }}
