apiVersion: v1
kind: Secret
metadata:
  name: nginx-password
{{- if .Values.rstudio.secret }}
data:
  {{- range $key, $val := .Values.rstudio.secret }}
    "{{ $key }}": "{{ tpl $val $ | b64enc }}"
  {{- end }}
{{- end }}
type: Opaque
