apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: rstudio
    port: 8787
    targetPort: 8787
  - name: shiny
    port: 3838
    targetPort: 3838

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-okd
spec:
  selector:
    app: nginx-okd
  ports:
  - name: 8081-tcp
    port: 8081
    targetPort: 8081