#################################
## Airflow Webserver Route (OKD)
#################################
{{- if .Values.route.enabled }}
{{- $fullname := (include "airflow.fullname" .) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  {{- with .Values.route.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    tier: airflow
    component: airflow-route
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  name: {{ $fullname }}-route
spec:
  host: ""
  port:
    targetPort: airflow-ui
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.route.insecureEdgeTerminationPolicy }}
    termination: {{ .Values.route.termination }}
  to:
    kind: Service
    name: {{ include "airflow.fullname" . }}-webserver
    weight: 100
  wildcardPolicy: None
{{- end }}
