apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.appName }}-config
data:
  grafana.ini: |
    [paths]
    data = /var/lib/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /usr/share/grafana/conf/provisioning

    [log]
    mode = console
    
    [security]
    admin_user = ${ADMIN_USER}
    admin_password = ${ADMIN_PASSWORD}

  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      org_id: 1
      url: http://prometheus-service:9090
      is_default: true
      version: 1
      editable: true
