apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.grafana.appName }}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.pvc.storageSize }}