apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.grafana.appName }}-route
spec:
  port:
    targetPort: 3000
  tls:
    termination: {{ .Values.grafana.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.grafana.route.tls.insecureEdgeTerminationPolicy }}
  to:
    kind: Service
    name: {{ .Values.grafana.appName }}-service