apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.appName }}
type: Opaque
stringData:
  admin-username: {{ .Values.grafana.secret.adminUsername }}
  admin-password: {{ .Values.grafana.secret.adminPassword | b64enc }}
