apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.appName }}
type: Opaque
{{- if .Values.grafana.secret}}
data:
  {{- range $key, $val := .Values.grafana.secret }}
    "{{ $key }}": "{{ tpl $val $ | b64enc }}"
  {{- end }}
{{- end }}