apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.appName }}-secret
type: Opaque
stringData:
  admin-username: {{ .Values.grafana.secret.adminUsername }}
  {{- include "grafana.secretPassword" . | nindent 2 }}