apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.appName }}-service
spec:
  ports:
  - name: {{ .Values.grafana.appName }}
    port: 3000
    targetPort: 3000
  selector:
    app: {{ .Values.grafana.appName }}
  type: {{ .Values.grafana.service.type }}