apiVersion: v2
name: mlflow
description: MLflow Helm Chart for Rahti platform
  Link to the repo https://github.com/CSCfi/helm-charts
icon: https://raw.githubusercontent.com/mlflow/mlflow/master/assets/logo.svg
type: application
version: 3.14.0
dependencies:
  - name: mlflow
    version: 3.14.0
    repository: ""
