apiVersion: v2
name: plausible
dependencies:
  - name: plausible-analytics
    alias: plausible
    repository: https://imio.github.io/helm-charts
    version: 0.4.x
description: Plausible Helm Chart for Rahti platform
  Link to the repo https://github.com/CSCfi/helm-charts
version: 1.5.0
sources:
- https://github.com/CSCfi/helm-charts
icon: https://plausible.io/uploads/plausible-community-edition.png