apiVersion: v2
name: gitlab-runner
description: GitLab Runner Helm Chart for Rahti platform
  Link to the repo https://github.com/CSCfi/helm-charts
version: 1.0.0
sources:
- https://gitlab.com/gitlab-org/charts/gitlab-runner
- https://gitlab.com/gitlab-org/gitlab-runner
- https://docs.gitlab.com/runner/
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/gitlab-runner/img/gitlab-runner-stack-220x234.png
dependencies:
  - name: gitlab-runner
    repository: https://charts.gitlab.io
    version: 0.92.x
