gitlab-runner:
  image:
    registry: registry.gitlab.com
    image: gitlab-org/ci-cd/gitlab-runner-ubi-images/gitlab-runner-ocp
    tag: v17.3.1

  gitlabUrl: https://gitlab.ci.csc.fi/

  runnerToken: ""

  podSecurityContext:
    runAsUser: null
    fsGroup: null

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: null
    privileged: false
    seccompProfile:
      type: "RuntimeDefault"
    capabilities:
      drop: ["ALL"]

  useTini: true

  serviceAccount:
    create: true
    name: "gitlab-runner"

  rbac:
    create: true
    serviceAccount:
      name: gitlab-runner
    rules:
      - resources: ["events"]
        verbs: ["list", "watch"]
      - resources: ["pods"]
        verbs: ["create","delete","get"]
      - apiGroups: [""]
        resources: ["pods/attach","pods/exec"]
        verbs: ["get","create","patch","delete"]
      - apiGroups: [""]
        resources: ["pods/log"]
        verbs: ["get","list"]
      - resources: ["secrets"]
        verbs: ["create","delete","get","update"]
      - resources: ["serviceaccounts"]
        verbs: ["get"]
      - resources: ["services"]
        verbs: ["create","get"]

  runners:
    config: |
      [[runners]]
        [runners.kubernetes]
          helper_image = "registry.gitlab.com/gitlab-org/ci-cd/gitlab-runner-ubi-images/gitlab-runner-helper-ocp:v17.3.1"
          [runners.kubernetes.pod_security_context]
            run_as_non_root = true
