# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: spark
      image: docker.io/bitnami/spark:3.5.0-debian-11-r16
apiVersion: v2
appVersion: 3.5.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Spark is a high-performance engine for large-scale computing tasks, such as data processing, machine learning and real-time data streaming. It includes APIs for Java, Python, Scala and R.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/spark/img/spark-stack-220x234.png
keywords:
- apache
- spark
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: spark
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/spark
version: 8.1.6
