apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.appName }}
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
spec:
  resources:
    limits:
      memory: 2Gi
  source:
    type: Git
    git:
      uri: {{ .Values.buildConfig.gitRepoUri }}
      ref: {{ .Values.buildConfig.gitBranch }}
    contextDir: {{ .Values.buildConfig.contextDir }}
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.appName }}:latest
  triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secretReference:
          name: webhooksecret
      type: GitHub
