apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
      app: {{ .Values.appName }}
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - image: {{ .Values.appName }}:latest
        imagePullPolicy: IfNotPresent
        name: {{ .Values.appName }}
        ports:
        - containerPort: 3838
          protocol: TCP
        - containerPort: 8787
          protocol: TCP
        volumeMounts:
        - name: {{ .Values.rstudio.pvc.mountName }}
          mountPath: /home/rstudio-server
        - name: {{ .Values.shiny.pvc.mountName }}
          mountPath: /srv/shiny-server
        {{- if .Values.openshift.enabled}}
        securityContext:
        {{- .Values.rstudio.containerSecurityContext | toYaml | nindent 10 }}
        {{- end }}
      {{- if .Values.openshift.enabled }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
      {{- .Values.rstudio.podSecurityContext | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .Values.rstudio.pvc.mountName }}
        persistentVolumeClaim:
          claimName: {{ .Values.rstudio.pvc.mountName }}
      - name: {{ .Values.shiny.pvc.mountName }}
        persistentVolumeClaim:
          claimName: {{ .Values.shiny.pvc.mountName }}
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ .Values.appName }}
      from:
        kind: ImageStreamTag
        name: {{ .Values.appName }}:latest
    type: ImageChange
