ingress:
  host: "jupyter.rahtiapp.fi"
resources:
  requests:
    cpu: 2
    memory: 2G
  limits:
    cpu: 4
    memory: 4G
persistentStorage:
  existingClaim: "spark-pvc"
  existingClaimName: "spark-pvc"
env:
  sparkMasterUrl: "local[*]"
  jupyterLab: false
<<<<<<< HEAD
dockerImage: quay.io/uninett/jupyter-spark:20180608-ed0d171
=======
dockerImage: apurva3000/spark-jupyter-openshift:20180601
>>>>>>> d7a4df4... jupyter for openshift
githubToken: ""
