kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.mongodb.appName }}-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.pvc.storageSize }}