kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.mongodb.appName }}
spec:
  ports:
    - name: mongo
      protocol: TCP
      port: {{ .Values.mongodb.service.ports.mongodb }}
      targetPort: {{ .Values.mongodb.service.ports.mongodb }}
  selector:
    name: {{ .Values.mongodb.appName }}
  type: {{ .Values.mongodb.service.type }}

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.rocketchat.appName }}-service
spec:
  ports:
    - name: 3000-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: {{ .Values.rocketchat.appName }}
  type: {{ .Values.rocketchat.service.type }}
