apiVersion: v2
name: hedgedoc-helm
description: Hedgedoc Helm Chart for Rahti platform
version: 1.0.0
sources:
- https://github.com/CSCfi/helm-charts
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
    version: 13.x.x