apiVersion: v2
name: hedgedoc-helm
description: Hedgedoc Helm Chart for Rahti platform
  Link to the repo https://github.com/CSCfi/helm-charts
version: 1.1.1
sources:
- https://github.com/CSCfi/helm-charts
icon: https://raw.githubusercontent.com/hedgedoc/hedgedoc/develop/frontend/src/app/icon.png
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
    version: 13.x.x