apiVersion: v2
name: hedgedoc
description: Hedgedoc Helm Chart for Rahti platform
  Link to the repo https://github.com/CSCfi/helm-charts
version: 1.2.1
sources:
- https://github.com/CSCfi/helm-charts
icon: https://raw.githubusercontent.com/hedgedoc/hedgedoc/develop/frontend/src/app/icon.png
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
    - bitnami-common
    version: 2.x.x
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
    version: 15.x.x
