global:
  route:
    host: "" # Edit this value
    insecureEdgeTerminationPolicy: Redirect
    termination: edge

matomo:
  global:
    security:
      allowInsecureImages: true

  matomoUsername: user
  matomoPassword: ""
  matomoEmail: ""

  customPostInitScripts:
    add-trusted-host.sh: |
      #!/bin/bash
      CONFIG_FILE="/bitnami/matomo/config/config.ini.php"
      if [ -f "$CONFIG_FILE" ] && ! grep -qF {{ .Values.global.route.host }} "$CONFIG_FILE"; then
        sed -i '/^\[General\]/a trusted_hosts[] = "'{{ .Values.global.route.host }}'"' "$CONFIG_FILE"
      fi

  image:
    registry: satama.csc.fi
    repository: library/matomo
    tag: 5.11.2
    debug: false

  allowEmptyPassword: false

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

  service:
    type: ClusterIP

  ### Since the change in the Bitnami catalog (https://github.com/bitnami/containers/issues/83267), deployment of MariaDB alongside Matomo using bitnami catalog is intended for testing/development purposes
  ### This image only uses the 'latest' tag, so it is not recommended in production.
  ### The image can be build from source: https://github.com/bitnami/containers/tree/main/bitnami/mariadb
  mariadb:
    enabled: true
    image:
      registry: satama.csc.fi
      repository: library/mariadb
      tag: 13.0.1
    architecture: standalone
    auth:
      rootPassword: ""
      database: matomo_db
      username: matomo
      password: ""
    primary:
      persistence:
        enabled: true
        size: 8Gi
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m

  externalDatabase:
    host: ""
    port: 3306
    user: matomo
    password: ""
    database: matomo_db
    existingSecret: ""

  metrics:
    enabled: false
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

  certificates:
    image:
      repository: bitnamisecure/os-shell
      tag: latest
