route:
  insecureEdgeTerminationPolicy: Redirect
  termination: edge 

matomo:
  ## @param matomoUsername User of the application
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/matomo#configuration
  ##
  matomoUsername: user
  ## @param matomoPassword Application password
  ## Defaults to a random 10-character alphanumeric string if not set
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/matomo#configuration
  ##
  matomoPassword: ""
  ## @param matomoEmail Admin email
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/matomo#configuration
  ##
  matomoEmail: user@example.com
  ## @param matomoWebsiteName Matomo application name
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/matomo#configuration
  ##
  ## @param allowEmptyPassword Allow DB blank passwords
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/matomo#environment-variables
  ##
  image:
    debug: false
  allowEmptyPassword: false
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
  mariadb:
    enabled: true
    primary:
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m
  externalDatabase:
    host: ""
    port: 3306
    user: bn_matomo
    password: ""
    database: bitnami_matomo
    existingSecret: ""
  metrics:
    enabled: false
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m