route:
  insecureEdgeTerminationPolicy: Redirect
  termination: edge 

matomo:
  global:
    security:
      allowInsecureImages: true
      
  matomoUsername: user
  matomoPassword: ""
  matomoEmail: user@example.com

  image:
    repository: bitnamilegacy/matomo
    tag: 5.3.2-debian-12-r11
    debug: false
  
  allowEmptyPassword: false
  
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  
  service:
    type: ClusterIP
  
  ### Since the change in the Bitnami catalog (https://github.com/bitnami/containers/issues/83267), deployment of MariaDB alongside Matomo using bitnami catalog is intended for testing/development purposes
  ### This image only uses the 'latest' tag, so it is not recommended in production.
  ### The image can be build from source: https://github.com/bitnami/containers/tree/main/bitnami/mariadb
  mariadb:
    enabled: true
    image:
      repository: bitnamisecure/mariadb
      tag: latest
    architecture: standalone
    auth:
      rootPassword: ""
      database: bitnami_matomo
      username: bn_matomo
      password: ""
    primary:
      persistence:
        enabled: true
        size: 8Gi
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m
  
  externalDatabase:
    host: ""
    port: 3306
    user: bn_matomo
    password: ""
    database: bitnami_matomo
    existingSecret: ""
  
  metrics:
    enabled: false
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

  certificates:
    image:
      repository: bitnamisecure/os-shell
      tag: latest