mariadb:
  image: image-registry.apps.2.rahti.csc.fi/openshift/mariadb:10.3-el8
  imageStream:
    name: mariadb
    tag: 10.3-el8
    namespace: openshift
  name: mariadb
  service:
    type: ClusterIP
  pvc:
    storageSize: 5Gi
    storageClassName: standard-csi
  random_pw_secret_key: database-password
  random_root_pw_secret_key: database-root-password
  secret:
    database-name: matomodb
    database-user: matomouser
    database-password: '{{- include "random_mariadb_pw_reusable" . -}}'
    database-root-password: '{{- include "random_mariadb_root_pw_reusable" . -}}'
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    timeoutSeconds: 1
  resources:
    limits:
      memory: 512Mi

matomo:
  image: bitnami/matomo:latest
  name: matomo
  service:
    type: ClusterIP
  route:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
  random_pw_secret_key: matomo-password
  secret:
    matomo-username: matomouser
    matomo-password: '{{- include "random_matomo_pw_reusable" . -}}'