apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.clusterName }}-secret
  labels:
    app: {{ .Values.minio.clusterName }}
type: Opaque                     # Unstructured secret
stringData:
  {{- include "minio.keys" . | nindent 2 }}
  