apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.clusterName }}
  labels:
    app: {{ .Values.minio.clusterName }}
{{- if .Values.minio.secret }}
data:
  {{- range $key, $val := .Values.minio.secret }}
    "{{ $key}}": "{{ tpl $val $ | b64enc }}"
  {{- end }}
{{- end }}
  