apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.minio.clusterName }}
  name: {{ .Values.minio.clusterName }}
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: 9001-console
    port: 9001
    protocol: TCP
  selector:
    app: {{ .Values.minio.clusterName }}
  type: {{ .Values.minio.service.type }}