apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mariadb.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.pvc.storageSize }}
  storageClassName: {{ .Values.mariadb.pvc.storageClassName }}