apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: matomo
  name: matomo
spec:
  host: matomo-{{ .Release.Namespace }}.rahtiapp.fi
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.route.insecureEdgeTerminationPolicy }}
    termination: {{ .Values.route.termination }}
  to:
    kind: Service
    name: {{ .Release.Name }}-matomo
    weight: 100
  wildcardPolicy: None
