apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: matomo
  name: matomo
spec:
  host: {{ .Values.global.route.host }}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.global.route.insecureEdgeTerminationPolicy }}
    termination: {{ .Values.global.route.termination }}
  to:
    kind: Service
    name: {{ .Release.Name }}
    weight: 100
  wildcardPolicy: None
