apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.matomo.name }}
  name: {{ .Values.matomo.name }}-app
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.matomo.route.tls.insecureEdgeTerminationPolicy }}
    termination: {{ .Values.matomo.route.tls.termination }}
  to:
    kind: Service
    name: {{ .Values.matomo.name }}-svc
    weight: 100