apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: {{ .Values.mariadb.name }}
stringData:
  database-name: {{ .Values.mariadb.secret.databaseName }}
  database-user: {{ .Values.mariadb.secret.databaseUser }}
  database-password: {{ .Values.mariadb.secret.databasePassword }}
  database-root-password: {{ .Values.mariadb.secret.rootPassword }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.matomo.name }}
stringData:
  matomo-username: {{ .Values.matomo.secret.matomoUser }}
  matomo-password: {{ .Values.matomo.secret.matomoPassword }}
type: Opaque