apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mariadb")].port}
  name: {{ .Values.mariadb.name }}
spec:
  ports:
  - name: mariadb
    port: 3306
  selector:
    name: {{ .Values.mariadb.name }}
  type: {{ .Values.mariadb.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.matomo.name }}
  name: {{ .Values.matomo.name }}-svc
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deploymentconfig: {{ .Values.matomo.name }}
  type: {{ .Values.matomo.service.type }}
