rahti:
  route:
    enabled: true
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

airflow:
  uid:
  gid:

  ingress:
    apiServer:
      enabled: false
      hosts: []
      path: /
    web:
      enabled: false
      hosts: []
      path: /
    flower:
      enabled: false
      hosts: []
      path: /
    statsd:
      enabled: false
      hosts: []
      path: /metrics
    pgbouncer:
      enabled: false
      hosts: []
      path: /metrics
  
  networkPolicies:
    enabled: false

  rbac:
    create: false
    createSCCRolebinding: false
  
  data:
    # oc create secret generic mydatabase --from-literal=connection=postgresql://<user>:<password>@<host>:5432/<database>
    metadataSecretName: ""

  # oc create secret generic myairflow-webserver-secret-key --from-literal="webserver-secret-key=$(python3 -c 'import secrets; print(secrets.token_hex(16))')"
  webserverSecretKey: ""
  
  workers:
    replicas: 1
    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 20
      failureThreshold: 5
      periodSeconds: 60
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 500m
    logGroomerSidecar:
      enabled: false
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m
    waitForMigrations:
      enabled: true
    safeToEvict: true

  scheduler:
    enabled: true
    startupProbe:
      initialDelaySeconds: 60
      failureThreshold: 30
      periodSeconds: 10
      timeoutSeconds: 50
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
    logGroomerSidecar:
      enabled: false
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m
    waitForMigrations:
      enabled: true
    safeToEvict: true

  createUserJob:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
  
  migrateDatabaseJob:
    enabled: true
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m

  apiServer:
    startupProbe:
      initialDelaySeconds: 120
      failureThreshold: 30
      periodSeconds: 10
      timeoutSeconds: 5
    replicas: 1
    waitForMigrations:
      enabled: true
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 2Gi
        cpu: 1000m
  
  webserver:
    enabled: true
    replicas: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    service:
      type: ClusterIP
    defaultUser:
      enabled: true
      role: Admin
      username: admin
      email: admin@example.com
      firstName: admin
      lastName: user
      password: admin
    waitForMigrations:
      enabled: true
  
  triggerer:
    enabled: true
    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 20
      failureThreshold: 5
      periodSeconds: 60
    replicas: 1
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    logGroomerSidecar:
      enabled: false
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m
    waitForMigrations:
      enabled: true
  
  dagProcessor:
    enabled: true
    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 20
      failureThreshold: 5
      periodSeconds: 60
    replicas: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    logGroomerSidecar:
      enabled: false
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m
    waitForMigrations:
      enabled: true

  flower:
    enabled: false

  statsd:
    enabled: false

  pgbouncer:
    enabled: false
    replicas: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    uid:

  redis:
    enabled: true
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 1Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    uid:

  elasticsearch:
    enabled: false
  
  opensearch:
    enabled: false

  cleanup:
    enabled: false

  postgresql:
    enabled: false
  
  logs:
    persistence:
      enabled: false
      size: 8Gi