---
# Source: jupyter-specifics/templates/route.yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: rahti-notebook
spec:
  to:
    kind: Service
    name: proxy-public
    weight: 100
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
