apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.appName }}-nginx-config
data:
  nginx.conf: |-
    http {
        server {
            listen 9091;
            location / {
                auth_basic           "Prometheus";
                auth_basic_user_file /etc/nginx/secrets/passwd;
                proxy_pass           http://localhost:9090/;
            }
        }
    }
    events {}