apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.prometheus.appName }}
  name: {{ .Values.prometheus.appName }}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.pvc.storageSize }}