apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prometheus.appName }}-nginx-secret
type: Opaque
stringData:
  user: {{ .Values.prometheus.secret.user }}
  {{- include "prometheus.secretPassword" . | nindent 2 }}