apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.appName }}-service
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: {{ .Values.prometheus.appName }}
  type: {{ .Values.prometheus.service.type }}