name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Add NATS Helm repo
        run: |
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/ &&
          helm repo update

      - name: Helm Dependency
        run: |
          for dir in $(ls -d charts/*); do
            helm dependency build $dir;
          done

#      - name: Helm Lint
#        run: |
#          for dir in $(ls -d charts/*); do
#            helm lint $dir
#          done
          
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
